name: Create docs with sphinx
on:
  push:
    branches: [ main ]
jobs:
  docs:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"          
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: Setup poetry
        run: "poetry install --no-interaction"
      - name: Build
        run: poetry run make -C docs/ html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./docs/_build/html/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
